namespace IRequest {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface DeleteItemBody {
    /**
     * 删除列表内容
     */
    listItems?: Item[];
    name?: string;
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface DeleteRequestBodyListItemsUsingDELETEParams {
    length?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type DeleteRequestBodyListItemsUsingDELETEBody = DeleteItemBody;

  export interface DeleteItemBody {
    /**
     * 删除列表内容
     */
    listItems?: Item[];
    name?: string;
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type DeleteRequestBodyListItemsUsingDELETEResponses = DeleteItemBody[];

  export interface DeleteItemBody {
    /**
     * 删除列表内容
     */
    listItems?: Item[];
    name?: string;
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface DeleteRequestSearchItemsUsingDELETEParams {
    length?: number;
    query?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type DeleteRequestSearchItemsUsingDELETEResponses = Item[];

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface DeleteRequestGetUserByIdUsingDELETEParams {
    id?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type DeleteRequestGetUserByIdUsingDELETEResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface DeleteRequestGetUserByIdsUsingDELETEParams {
    id?: number;
    spanceId?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type DeleteRequestGetUserByIdsUsingDELETEResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface GetRequestBodyListItemsUsingGETParams {
    length?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type GetRequestBodyListItemsUsingGETBody = ItemBody;

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type GetRequestBodyListItemsUsingGETResponses = ItemBody[];

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PutRequestBodyListItemsUsingPUTParams {
    length?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PutRequestBodyListItemsUsingPUTBody = ItemBody;

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PutRequestBodyListItemsUsingPUTResponses = ItemBody[];

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PostRequestBodyListItemsUsingPOSTParams {
    length?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PostRequestBodyListItemsUsingPOSTBody = ItemBody;

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PostRequestBodyListItemsUsingPOSTResponses = ItemBody[];

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PatchRequestBodyListItemsUsingPATCHParams {
    length?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PatchRequestBodyListItemsUsingPATCHBody = ItemBody;

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PatchRequestBodyListItemsUsingPATCHResponses = ItemBody[];

  export interface ItemBody {
    listItems?: Item[];
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述
     */
    text?: string;
  }
  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface GetRequestSearchItemsUsingGETParams {
    length?: number;
    query?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type GetRequestSearchItemsUsingGETResponses = Item[];

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PutRequestSearchItemsUsingPUTParams {
    length?: number;
    query?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PutRequestSearchItemsUsingPUTResponses = Item[];

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PostRequestSearchItemsUsingPOSTParams {
    length?: number;
    query?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PostRequestSearchItemsUsingPOSTResponses = Item[];

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PatchRequestSearchItemsUsingPATCHParams {
    length?: number;
    query?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PatchRequestSearchItemsUsingPATCHResponses = Item[];

  export interface Item {
    number?: number;
    text?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface GetRequestGetUserByIdUsingGETParams {
    id?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type GetRequestGetUserByIdUsingGETResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PutRequestGetUserByIdUsingPUTParams {
    id?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PutRequestGetUserByIdUsingPUTResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PostRequestGetUserByIdUsingPOSTParams {
    id?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PostRequestGetUserByIdUsingPOSTResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PatchRequestGetUserByIdUsingPATCHParams {
    id?: number;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PatchRequestGetUserByIdUsingPATCHResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface GetRequestGetUserByIdsUsingGETParams {
    id?: number;
    spanceId?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type GetRequestGetUserByIdsUsingGETResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PutRequestGetUserByIdsUsingPUTParams {
    id?: number;
    spanceId?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PutRequestGetUserByIdsUsingPUTResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PostRequestGetUserByIdsUsingPOSTParams {
    id?: number;
    spanceId?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PostRequestGetUserByIdsUsingPOSTResponses = string;
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export interface PatchRequestGetUserByIdsUsingPATCHParams {
    id?: number;
    spanceId?: string;
  }
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  export type PatchRequestGetUserByIdsUsingPATCHResponses = string;
}
